In [1]:
%%javascript
require(["codemirror/keymap/sublime", "notebook/js/cell", "base/js/namespace"],
    function(sublime_keymap, cell, IPython){
        cell.Cell.options_default.cm_config.keyMap = 'sublime';
        var cells = IPython.notebook.get_cells();
        for(var cl=0; cl< cells.length ; cl++){
            cells[cl].code_mirror.setOption('keyMap', 'sublime');
        }
    }
);

In [2]:
import numpy as np
import pandas as pd
from tqdm.auto import tqdm
import matplotlib.pyplot as plt
%matplotlib inline

#### Load lite results from log file

In [9]:
import ast

test_log = pd.read_excel('results/df/test_log.xlsx').drop(['Unnamed: 0'],axis=1)
test_log['n_features'] = [len(ast.literal_eval(item)) for item in test_log['features']]
test_log.round(3).tail()

,auto_train,added_features,oversample,features,train_size,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
341,1,1,1,"['age', 'sex', 'smoking', 'high_blood_pressure...",0.66,100,df453,0.686,0.744,0.531,0.823,0.404,0.256,0.779,5
342,1,1,1,"['age', 'sex', 'smoking', 'high_blood_pressure...",0.66,100,df454,0.570,0.736,0.386,0.579,0.555,0.264,0.643,5
343,1,1,1,"['age', 'sex', 'smoking', 'platelets', 'serum_...",0.66,100,df455,0.629,0.755,0.443,0.672,0.543,0.245,0.708,5
344,1,1,1,"['age', 'sex', 'smoking', 'platelets', 'serum_...",0.66,100,df456,0.579,0.738,0.398,0.585,0.566,0.262,0.651,5
345,1,1,1,"['age', 'sex', 'smoking', 'serum_creatinine', ...",0.66,100,df457,0.631,0.757,0.444,0.675,0.542,0.243,0.711,5

#### Time to actually do something

In [13]:
query = {
    'auto_train': False,
    'oversample': True,
    'n_features': 5
}
query_str = ''
for key in query.keys():
    query_str = query_str + f'{key} == @query["{key}"] & ' 
query_str = query_str[:-2]

test_log_sorted = test_log.sort_values(by=['selectivity'],ascending=False).round(3)
test_log_sorted.head(10)

,auto_train,added_features,oversample,features,train_size,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
178,1,1,0,"['sex', 'smoking']",0.66,100,df178,0.690,0.689,0.753,0.995,0.034,0.311,0.813,2
68,0,0,0,"['sex', 'smoking']",0.66,100,df68,0.679,0.679,0.692,0.995,0.021,0.321,0.807,2
120,0,0,1,"['serum_creatinine', 'smoking']",0.66,100,df120,0.754,0.774,0.689,0.907,0.424,0.226,0.834,2
65,0,0,0,"['serum_creatinine', 'smoking']",0.66,100,df65,0.740,0.754,0.685,0.916,0.372,0.246,0.826,2
41,0,0,0,"['diabetes', 'ejection_fraction']",0.66,100,df41,0.701,0.724,0.616,0.906,0.281,0.276,0.803,2
84,0,0,1,"['anaemia', 'serum_creatinine']",0.66,100,df84,0.712,0.741,0.615,0.887,0.348,0.259,0.805,2
257,0,0,0,"['age', 'sex', 'smoking', 'high_blood_pressure...",0.66,100,df369,0.710,0.732,0.614,0.904,0.301,0.268,0.808,5
110,0,0,1,"['high_blood_pressure', 'serum_creatinine']",0.66,100,df110,0.715,0.744,0.612,0.888,0.350,0.256,0.808,2
55,0,0,0,"['high_blood_pressure', 'serum_creatinine']",0.66,100,df55,0.700,0.725,0.605,0.896,0.298,0.275,0.800,2
230,1,1,1,"['serum_creatinine', 'smoking']",0.66,100,df230,0.724,0.771,0.603,0.848,0.463,0.229,0.805,2