In [1]:
%%javascript
require(["codemirror/keymap/sublime", "notebook/js/cell", "base/js/namespace"],
    function(sublime_keymap, cell, IPython){
        cell.Cell.options_default.cm_config.keyMap = 'sublime';
        var cells = IPython.notebook.get_cells();
        for(var cl=0; cl< cells.length ; cl++){
            cells[cl].code_mirror.setOption('keyMap', 'sublime');
        }
    }
);

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

#### Load lite results from log file

In [23]:
import ast

test_log = pd.read_excel('results/df/test_log.xlsx').drop(['Unnamed: 0'],axis=1)
test_log['n_features'] = [len(ast.literal_eval(item)) for item in test_log['features']]
test_log.round(3).tail()

,auto_train,added_features,oversample,features,train_size,stratified,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
589,True,1,True,"['serum_creatinine', 'sex']",0.66,False,100,df589,0.678,0.395,0.811,0.501,0.742,0.605,0.435,2
590,True,1,True,"['serum_creatinine', 'smoking']",0.66,False,100,df590,0.729,0.466,0.853,0.614,0.773,0.534,0.520,2
591,True,1,True,"['serum_sodium', 'sex']",0.66,False,100,df591,0.573,0.544,0.588,0.385,0.734,0.456,0.445,2
592,True,1,True,"['serum_sodium', 'smoking']",0.66,False,100,df592,0.566,0.564,0.571,0.386,0.735,0.436,0.451,2
593,True,1,True,"['sex', 'smoking']",0.66,False,100,df593,0.460,0.620,0.392,0.317,0.695,0.380,0.408,2

#### Results by category: all features

In [13]:
query = {
    'n_features': 11
}
query_str = ''
for key in query.keys():
    query_str = query_str + f'{key} == @query["{key}"] & ' 
query_str = query_str[:-2]

test_log_sorted = test_log.query(query_str).sort_values(by=['recall'],ascending=False).round(3)
test_log_sorted.head(10)

,auto_train,added_features,oversample,features,train_size,stratified,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
5,True,1,True,"['age', 'anaemia', 'creatinine_phosphokinase',...",0.66,False,100,df5,0.700,0.646,0.725,0.522,0.817,0.354,0.574,11
7,True,1,True,"['age', 'anaemia', 'creatinine_phosphokinase',...",0.66,True,100,df7,0.693,0.634,0.720,0.517,0.809,0.366,0.566,11
1,False,0,True,"['age', 'anaemia', 'creatinine_phosphokinase',...",0.66,False,100,df1,0.687,0.631,0.716,0.524,0.799,0.369,0.568,11
2,False,0,True,"['age', 'anaemia', 'creatinine_phosphokinase',...",0.66,True,100,df2,0.687,0.618,0.720,0.506,0.805,0.382,0.553,11
3,False,0,False,"['age', 'anaemia', 'creatinine_phosphokinase',...",0.66,True,100,df3,0.666,0.504,0.744,0.489,0.759,0.496,0.493,11
0,False,0,False,"['age', 'anaemia', 'creatinine_phosphokinase',...",0.66,False,100,df0,0.668,0.497,0.752,0.492,0.757,0.503,0.489,11
6,True,1,False,"['age', 'anaemia', 'creatinine_phosphokinase',...",0.66,True,100,df6,0.677,0.492,0.766,0.504,0.760,0.508,0.495,11
4,True,1,False,"['age', 'anaemia', 'creatinine_phosphokinase',...",0.66,False,100,df4,0.667,0.477,0.757,0.479,0.757,0.523,0.473,11

#### Results by category: no autotrain, no oversample, random sampling, 2 features

In [14]:
query = {
    'auto_train': False,
    'oversample': False,
    'n_features': 2,
    'stratified': False
}
query_str = ''
for key in query.keys():
    query_str = query_str + f'{key} == @query["{key}"] & ' 
query_str = query_str[:-2]

test_log_sorted = test_log.query(query_str).sort_values(by=['recall'],ascending=False).round(3)
test_log_sorted.head(5)

,auto_train,added_features,oversample,features,train_size,stratified,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
44,False,0,False,"['ejection_fraction', 'serum_creatinine']",0.66,False,100,df44,0.726,0.517,0.829,0.602,0.778,0.483,0.550,2
31,False,0,False,"['creatinine_phosphokinase', 'serum_creatinine']",0.66,False,100,df31,0.671,0.469,0.770,0.496,0.752,0.531,0.476,2
11,False,0,False,"['age', 'ejection_fraction']",0.66,False,100,df11,0.698,0.446,0.819,0.541,0.758,0.554,0.483,2
14,False,0,False,"['age', 'serum_creatinine']",0.66,False,100,df14,0.660,0.432,0.770,0.475,0.739,0.568,0.449,2
32,False,0,False,"['creatinine_phosphokinase', 'serum_sodium']",0.66,False,100,df32,0.622,0.420,0.720,0.414,0.725,0.580,0.410,2

#### Results by category: no autotrain, oversample, random sampling, 2 features

In [15]:
query = {
    'auto_train': False,
    'oversample': True,
    'n_features': 2,
    'stratified': False
}
query_str = ''
for key in query.keys():
    query_str = query_str + f'{key} == @query["{key}"] & ' 
query_str = query_str[:-2]

test_log_sorted = test_log.query(query_str).sort_values(by=['recall'],ascending=False).round(3)
test_log_sorted.head(5)

,auto_train,added_features,oversample,features,train_size,stratified,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
87,False,0,True,"['creatinine_phosphokinase', 'serum_sodium']",0.66,False,100,df87,0.613,0.620,0.612,0.430,0.774,0.380,0.504,2
117,False,0,True,"['sex', 'smoking']",0.66,False,100,df117,0.463,0.582,0.417,0.310,0.690,0.418,0.391,2
99,False,0,True,"['ejection_fraction', 'serum_creatinine']",0.66,False,100,df99,0.727,0.568,0.804,0.583,0.795,0.432,0.570,2
86,False,0,True,"['creatinine_phosphokinase', 'serum_creatinine']",0.66,False,100,df86,0.658,0.567,0.705,0.489,0.768,0.433,0.520,2
109,False,0,True,"['platelets', 'serum_sodium']",0.66,False,100,df109,0.578,0.556,0.591,0.397,0.735,0.444,0.459,2

#### Results by category: autotrain, no oversample, random sampling, 2 features

In [16]:
query = {
    'auto_train': True,
    'oversample': False,
    'n_features': 2,
    'stratified': False
}
query_str = ''
for key in query.keys():
    query_str = query_str + f'{key} == @query["{key}"] & ' 
query_str = query_str[:-2]

test_log_sorted = test_log.query(query_str).sort_values(by=['recall'],ascending=False).round(3)
test_log_sorted.head(5)

,auto_train,added_features,oversample,features,train_size,stratified,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
154,True,1,False,"['ejection_fraction', 'serum_creatinine']",0.66,False,100,df154,0.725,0.603,0.780,0.561,0.812,0.397,0.576,2
121,True,1,False,"['age', 'ejection_fraction']",0.66,False,100,df121,0.671,0.516,0.744,0.480,0.771,0.484,0.491,2
124,True,1,False,"['age', 'serum_creatinine']",0.66,False,100,df124,0.638,0.486,0.710,0.438,0.749,0.514,0.456,2
167,True,1,False,"['serum_creatinine', 'serum_sodium']",0.66,False,100,df167,0.625,0.477,0.698,0.432,0.737,0.523,0.447,2
141,True,1,False,"['creatinine_phosphokinase', 'serum_creatinine']",0.66,False,100,df141,0.662,0.475,0.749,0.467,0.756,0.525,0.466,2

#### Results by category: no autotrain, no oversample, stratified sampling, 2 features

In [21]:
query = {
    'auto_train': False,
    'oversample': False,
    'n_features': 2,
    'stratified': True
}
query_str = ''
for key in query.keys():
    query_str = query_str + f'{key} == @query["{key}"] & ' 
query_str = query_str[:-2]

test_log_sorted = test_log.query(query_str).sort_values(by=['recall'],ascending=False).round(3)
test_log_sorted.head(5)

,auto_train,added_features,oversample,features,train_size,stratified,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
209,False,0,False,"['ejection_fraction', 'serum_creatinine']",0.66,True,100,df209,0.732,0.514,0.837,0.607,0.784,0.486,0.551,2
196,False,0,False,"['creatinine_phosphokinase', 'serum_creatinine']",0.66,True,100,df196,0.667,0.481,0.756,0.488,0.754,0.519,0.480,2
197,False,0,False,"['creatinine_phosphokinase', 'serum_sodium']",0.66,True,100,df197,0.627,0.423,0.725,0.425,0.725,0.577,0.421,2
176,False,0,False,"['age', 'ejection_fraction']",0.66,True,100,df176,0.692,0.419,0.823,0.536,0.748,0.581,0.466,2
179,False,0,False,"['age', 'serum_creatinine']",0.66,True,100,df179,0.669,0.418,0.789,0.489,0.740,0.582,0.447,2

 #### Results by category: autotrain, oversample, random sampling, 2 features

In [24]:
query = {
    'auto_train': True,
    'oversample': True,
    'n_features': 2,
    'stratified': False
}
query_str = ''
for key in query.keys():
    query_str = query_str + f'{key} == @query["{key}"] & ' 
query_str = query_str[:-2]

test_log_sorted = test_log.query(query_str).sort_values(by=['recall'],ascending=False).round(3)
test_log_sorted.head(5)

,auto_train,added_features,oversample,features,train_size,stratified,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
575,True,1,True,"['ejection_fraction', 'serum_creatinine']",0.66,False,100,df575,0.716,0.640,0.753,0.553,0.816,0.360,0.588,2
563,True,1,True,"['creatinine_phosphokinase', 'serum_sodium']",0.66,False,100,df563,0.604,0.623,0.595,0.427,0.767,0.377,0.503,2
593,True,1,True,"['sex', 'smoking']",0.66,False,100,df593,0.460,0.620,0.392,0.317,0.695,0.380,0.408,2
542,True,1,True,"['age', 'ejection_fraction']",0.66,False,100,df542,0.666,0.596,0.701,0.484,0.788,0.404,0.528,2
586,True,1,True,"['platelets', 'sex']",0.66,False,100,df586,0.537,0.582,0.518,0.363,0.725,0.418,0.444,2