In [1]:
%%javascript
require(["codemirror/keymap/sublime", "notebook/js/cell", "base/js/namespace"],
    function(sublime_keymap, cell, IPython){
        cell.Cell.options_default.cm_config.keyMap = 'sublime';
        var cells = IPython.notebook.get_cells();
        for(var cl=0; cl< cells.length ; cl++){
            cells[cl].code_mirror.setOption('keyMap', 'sublime');
        }
    }
);

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

#### Load lite results from log file

In [18]:
import ast

test_log = pd.read_excel('results/df/test_log.xlsx').drop(['Unnamed: 0'],axis=1)
test_log['n_features'] = [len(ast.literal_eval(item)) for item in test_log['features']]
test_log.round(3).tail()

,auto_train,added_features,oversample,features,train_size,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
331,True,1,True,"['age', 'sex', 'smoking', 'high_blood_pressure...",0.66,100,df331,0.679,0.392,0.818,0.517,0.739,0.608,0.437,5
332,True,1,True,"['age', 'sex', 'smoking', 'high_blood_pressure...",0.66,100,df332,0.570,0.531,0.591,0.380,0.729,0.469,0.437,5
333,True,1,True,"['age', 'sex', 'smoking', 'platelets', 'serum_...",0.66,100,df333,0.630,0.533,0.676,0.437,0.755,0.467,0.477,5
334,True,1,True,"['age', 'sex', 'smoking', 'platelets', 'serum_...",0.66,100,df334,0.579,0.570,0.586,0.390,0.747,0.430,0.459,5
335,True,1,True,"['age', 'sex', 'smoking', 'serum_creatinine', ...",0.66,100,df335,0.626,0.535,0.670,0.432,0.755,0.465,0.474,5

#### Results by category: all features

In [9]:
query = {
    'n_features': 11
}
query_str = ''
for key in query.keys():
    query_str = query_str + f'{key} == @query["{key}"] & ' 
query_str = query_str[:-2]

test_log_sorted = test_log.query(query_str).sort_values(by=['recall'],ascending=False).round(3)
test_log_sorted.head(5)

,auto_train,added_features,oversample,features,train_size,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
1,False,0,True,"['age', 'anaemia', 'creatinine_phosphokinase',...",0.66,100,df1,0.701,0.655,0.724,0.533,0.814,0.345,0.584,11
3,True,1,True,"['age', 'anaemia', 'creatinine_phosphokinase',...",0.66,100,df3,0.695,0.626,0.730,0.529,0.802,0.374,0.570,11
2,True,1,False,"['age', 'anaemia', 'creatinine_phosphokinase',...",0.66,100,df2,0.676,0.498,0.759,0.491,0.766,0.502,0.490,11
0,False,0,False,"['age', 'anaemia', 'creatinine_phosphokinase',...",0.66,100,df0,0.678,0.496,0.765,0.501,0.764,0.504,0.492,11

#### Results by category: no autotrain, no oversample, 2 features

In [8]:
query = {
    'auto_train': False,
    'oversample': False,
    'n_features': 2
}
query_str = ''
for key in query.keys():
    query_str = query_str + f'{key} == @query["{key}"] & ' 
query_str = query_str[:-2]

test_log_sorted = test_log.query(query_str).sort_values(by=['recall'],ascending=False).round(3)
test_log_sorted.head(5)

,auto_train,added_features,oversample,features,train_size,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
40,False,0,False,"['ejection_fraction', 'serum_creatinine']",0.66,100,df40,0.729,0.500,0.840,0.604,0.777,0.500,0.541,2
27,False,0,False,"['creatinine_phosphokinase', 'serum_creatinine']",0.66,100,df27,0.666,0.474,0.760,0.490,0.750,0.526,0.476,2
49,False,0,False,"['platelets', 'serum_creatinine']",0.66,100,df49,0.633,0.432,0.727,0.422,0.736,0.568,0.422,2
7,False,0,False,"['age', 'ejection_fraction']",0.66,100,df7,0.691,0.426,0.819,0.533,0.750,0.574,0.466,2
28,False,0,False,"['creatinine_phosphokinase', 'serum_sodium']",0.66,100,df28,0.615,0.425,0.710,0.415,0.719,0.575,0.415,2

#### Results by category: no autotrain, oversample, 2 features

In [10]:
query = {
    'auto_train': False,
    'oversample': True,
    'n_features': 2
}
query_str = ''
for key in query.keys():
    query_str = query_str + f'{key} == @query["{key}"] & ' 
query_str = query_str[:-2]

test_log_sorted = test_log.query(query_str).sort_values(by=['recall'],ascending=False).round(3)
test_log_sorted.head(5)

,auto_train,added_features,oversample,features,train_size,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
83,False,0,True,"['creatinine_phosphokinase', 'serum_sodium']",0.66,100,df83,0.603,0.611,0.601,0.416,0.769,0.389,0.491,2
95,False,0,True,"['ejection_fraction', 'serum_creatinine']",0.66,100,df95,0.731,0.577,0.806,0.588,0.800,0.423,0.577,2
105,False,0,True,"['platelets', 'serum_sodium']",0.66,100,df105,0.584,0.570,0.591,0.393,0.749,0.430,0.462,2
81,False,0,True,"['creatinine_phosphokinase', 'platelets']",0.66,100,df81,0.581,0.558,0.593,0.391,0.741,0.442,0.457,2
82,False,0,True,"['creatinine_phosphokinase', 'serum_creatinine']",0.66,100,df82,0.651,0.557,0.699,0.476,0.764,0.443,0.508,2

#### Results by category: autotrain, no oversample, 2 features

In [12]:
query = {
    'auto_train': True,
    'oversample': False,
    'n_features': 2
}
query_str = ''
for key in query.keys():
    query_str = query_str + f'{key} == @query["{key}"] & ' 
query_str = query_str[:-2]

test_log_sorted = test_log.query(query_str).sort_values(by=['recall'],ascending=False).round(3)
test_log_sorted.head(5)

,auto_train,added_features,oversample,features,train_size,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
150,True,1,False,"['ejection_fraction', 'serum_creatinine']",0.66,100,df150,0.718,0.604,0.774,0.556,0.808,0.396,0.572,2
117,True,1,False,"['age', 'ejection_fraction']",0.66,100,df117,0.668,0.523,0.742,0.500,0.761,0.477,0.506,2
138,True,1,False,"['creatinine_phosphokinase', 'serum_sodium']",0.66,100,df138,0.625,0.464,0.701,0.423,0.735,0.536,0.438,2
137,True,1,False,"['creatinine_phosphokinase', 'serum_creatinine']",0.66,100,df137,0.652,0.461,0.744,0.458,0.746,0.539,0.454,2
120,True,1,False,"['age', 'serum_creatinine']",0.66,100,df120,0.640,0.460,0.726,0.440,0.745,0.540,0.443,2

 #### Results by category: autotrain, oversample, 2 features

In [21]:
query = {
    'auto_train': True,
    'oversample': True,
    'n_features': 2
}
query_str = ''
for key in query.keys():
    query_str = query_str + f'{key} == @query["{key}"] & ' 
query_str = query_str[:-2]

test_log_sorted = test_log.query(query_str).sort_values(by=['recall'],ascending=False).round(3)
test_log_sorted.head(5)

,auto_train,added_features,oversample,features,train_size,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
205,True,1,True,"['ejection_fraction', 'serum_creatinine']",0.66,100,df205,0.716,0.653,0.746,0.544,0.825,0.347,0.589,2
193,True,1,True,"['creatinine_phosphokinase', 'serum_sodium']",0.66,100,df193,0.601,0.616,0.597,0.420,0.766,0.384,0.496,2
223,True,1,True,"['sex', 'smoking']",0.66,100,df223,0.463,0.612,0.394,0.320,0.687,0.388,0.411,2
172,True,1,True,"['age', 'ejection_fraction']",0.66,100,df172,0.656,0.592,0.689,0.476,0.780,0.408,0.523,2
183,True,1,True,"['anaemia', 'platelets']",0.66,100,df183,0.537,0.571,0.522,0.361,0.720,0.429,0.439,2

 #### Results by category: no autotrain, no oversample, 5 features

In [24]:
query = {
    'auto_train': False,
    'oversample': False,
    'n_features': 5
}
query_str = ''
for key in query.keys():
    query_str = query_str + f'{key} == @query["{key}"] & ' 
query_str = query_str[:-2]

test_log_sorted = test_log.query(query_str).sort_values(by=['recall'],ascending=False).round(3)
test_log_sorted.head(5)

,auto_train,added_features,oversample,features,train_size,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
244,False,0,False,"['age', 'sex', 'smoking', 'ejection_fraction',...",0.66,100,df244,0.729,0.515,0.834,0.604,0.781,0.485,0.549,5
235,False,0,False,"['age', 'sex', 'smoking', 'creatinine_phosphok...",0.66,100,df235,0.663,0.457,0.765,0.488,0.744,0.543,0.467,5
236,False,0,False,"['age', 'sex', 'smoking', 'creatinine_phosphok...",0.66,100,df236,0.624,0.443,0.710,0.417,0.732,0.557,0.425,5
249,False,0,False,"['age', 'sex', 'smoking', 'platelets', 'serum_...",0.66,100,df249,0.620,0.411,0.720,0.410,0.722,0.589,0.405,5
251,False,0,False,"['age', 'sex', 'smoking', 'serum_creatinine', ...",0.66,100,df251,0.678,0.404,0.809,0.509,0.741,0.596,0.444,5

#### Results by category: no autotrain, oversample, 5 features

In [14]:
query = {
    'auto_train': False,
    'oversample': True,
    'n_features': 5
}
query_str = ''
for key in query.keys():
    query_str = query_str + f'{key} == @query["{key}"] & ' 
query_str = query_str[:-2]

test_log_sorted = test_log.query(query_str).sort_values(by=['recall'],ascending=False).round(3)
test_log_sorted.head(5)

,auto_train,added_features,oversample,features,train_size,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
264,False,0,True,"['age', 'sex', 'smoking', 'creatinine_phosphok...",0.66,100,df264,0.612,0.614,0.613,0.430,0.770,0.386,0.502,5
272,False,0,True,"['age', 'sex', 'smoking', 'ejection_fraction',...",0.66,100,df272,0.728,0.580,0.799,0.575,0.804,0.420,0.571,5
263,False,0,True,"['age', 'sex', 'smoking', 'creatinine_phosphok...",0.66,100,df263,0.656,0.563,0.701,0.475,0.772,0.437,0.510,5
262,False,0,True,"['age', 'sex', 'smoking', 'creatinine_phosphok...",0.66,100,df262,0.575,0.554,0.586,0.383,0.741,0.446,0.449,5
278,False,0,True,"['age', 'sex', 'smoking', 'platelets', 'serum_...",0.66,100,df278,0.584,0.549,0.601,0.387,0.745,0.451,0.450,5

#### Results by category: autotrain, no oversample, 5 features

In [15]:
query = {
    'auto_train': True,
    'oversample': False,
    'n_features': 5
}
query_str = ''
for key in query.keys():
    query_str = query_str + f'{key} == @query["{key}"] & ' 
query_str = query_str[:-2]

test_log_sorted = test_log.query(query_str).sort_values(by=['recall'],ascending=False).round(3)
test_log_sorted.head(5)

,auto_train,added_features,oversample,features,train_size,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
300,True,1,False,"['age', 'sex', 'smoking', 'ejection_fraction',...",0.66,100,df300,0.719,0.585,0.781,0.556,0.804,0.415,0.566,5
291,True,1,False,"['age', 'sex', 'smoking', 'creatinine_phosphok...",0.66,100,df291,0.658,0.480,0.745,0.480,0.747,0.520,0.475,5
307,True,1,False,"['age', 'sex', 'smoking', 'serum_creatinine', ...",0.66,100,df307,0.624,0.472,0.698,0.431,0.734,0.528,0.446,5
292,True,1,False,"['age', 'sex', 'smoking', 'creatinine_phosphok...",0.66,100,df292,0.620,0.457,0.699,0.419,0.732,0.543,0.433,5
301,True,1,False,"['age', 'sex', 'smoking', 'ejection_fraction',...",0.66,100,df301,0.632,0.453,0.718,0.426,0.741,0.547,0.433,5

#### Results by category: autotrain, oversample, 5 features

In [19]:
query = {
    'auto_train': True,
    'oversample': True,
    'n_features': 5
}
query_str = ''
for key in query.keys():
    query_str = query_str + f'{key} == @query["{key}"] & ' 
query_str = query_str[:-2]

test_log_sorted = test_log.query(query_str).sort_values(by=['recall'],ascending=False).round(3)
test_log_sorted.head(5)

,auto_train,added_features,oversample,features,train_size,robustness_iterations,results_df,accuracy,recall,selectivity,precision,NPV,FNR,F1_measure,n_features
328,True,1,True,"['age', 'sex', 'smoking', 'ejection_fraction',...",0.66,100,df328,0.714,0.638,0.753,0.563,0.809,0.362,0.593,5
320,True,1,True,"['age', 'sex', 'smoking', 'creatinine_phosphok...",0.66,100,df320,0.595,0.607,0.590,0.416,0.758,0.393,0.490,5
334,True,1,True,"['age', 'sex', 'smoking', 'platelets', 'serum_...",0.66,100,df334,0.579,0.570,0.586,0.390,0.747,0.430,0.459,5
318,True,1,True,"['age', 'sex', 'smoking', 'creatinine_phosphok...",0.66,100,df318,0.575,0.567,0.581,0.393,0.738,0.433,0.460,5
319,True,1,True,"['age', 'sex', 'smoking', 'creatinine_phosphok...",0.66,100,df319,0.657,0.563,0.702,0.473,0.773,0.437,0.510,5